# Generated by Django 3.1.6 on 2021-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emial', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('address', models.TextField(max_length=200)),
                ('address2', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
